// src/pages/Profile.vue
<template>
  <div class="min-h-screen bg-[#0F1C2D]">
    <div class="relative h-64 md:h-80">
      <img :src="mockUser.coverImage" :alt="''" class="w-full h-full object-cover" />
      <div class="absolute inset-0 bg-gradient-to-t from-[#0F1C2D] via-transparent to-transparent"></div>
    </div>

    <div class="max-w-6xl mx-auto px-4 -mt-24 relative">
      <div class="flex flex-col md:flex-row gap-6">
        <div class="flex-shrink-0">
          <img :src="mockUser.avatar" :alt="mockUser.username" class="w-32 h-32 md:w-40 md:h-40 rounded-full border-4 border-[#4A5F8B] object-cover" />
        </div>
        <div class="flex-1">
          <div class="flex flex-wrap items-center gap-3 mb-2">
            <h1 class="text-2xl md:text-3xl font-bold text-white">{{ mockUser.username }}</h1>
            <span class="px-3 py-1 bg-[#4A5F8B]/20 text-[#4A5F8B] text-sm rounded-full">
              {{ mockUser.level }}
            </span>
            <span class="px-3 py-1 bg-gradient-to-r from-purple-500 to-pink-500 text-white text-sm rounded-full">
              {{ mockUser.memberStatus }}
            </span>
          </div>
          <p class="text-[#B8C6D8] mb-4">{{ mockUser.bio }}</p>
          
          <div class="flex flex-wrap items-center gap-6 mb-4">
            <div class="text-center">
              <p class="text-xl font-bold text-white">{{ mockUser.posts }}</p>
              <p class="text-xs text-[#6B7C93]">作品</p>
            </div>
            <div class="text-center">
              <p class="text-xl font-bold text-white">{{ mockUser.followers }}</p>
              <p class="text-xs text-[#6B7C93]">粉丝</p>
            </div>
            <div class="text-center">
              <p class="text-xl font-bold text-white">{{ mockUser.following }}</p>
              <p class="text-xs text-[#6B7C93]">关注</p>
            </div>
            <div class="text-center">
              <p class="text-xl font-bold text-white">{{ mockUser.memberDaysLeft }}</p>
              <p class="text-xs text-[#6B7C93]">会员剩余天数</p>
            </div>
          </div>

          <div class="flex flex-wrap gap-3">
            <button class="px-4 py-2 bg-[#4A5F8B] text-white rounded-lg hover:bg-[#6B7C93] transition-colors">
              <i class="fa-solid fa-plus mr-1"></i> 关注
            </button>
            <button class="px-4 py-2 border border-[#4A5F8B] text-[#4A5F8B] rounded-lg hover:bg-[#4A5F8B]/10 transition-colors">
              <i class="fa-solid fa-message-circle mr-1"></i> 私信
            </button>
            <button class="px-4 py-2 border border-[#4A5F8B] text-[#4A5F8B] rounded-lg hover:bg-[#4A5F8B]/10 transition-colors">
              <i class="fa-solid fa-ellipsis-h"></i>
            </button>
          </div>
        </div>
      </div>

      <div class="mt-8">
        <div class="flex items-center gap-2 mb-4">
          <div class="flex-1 h-1 bg-[#1E2532] rounded-full overflow-hidden">
            <div 
              class="h-full bg-gradient-to-r from-[#4A5F8B] to-blue-400 transition-all duration-500"
              :style="{ width: `${(mockUser.progress / mockUser.progressMax) * 100}%` }"
            ></div>
          </div>
          <span class="text-sm text-[#6B7C93]">{{ mockUser.progress }}/{{ mockUser.progressMax }} EXP</span>
        </div>
        <div class="flex items-center gap-2">
          <span v-for="i in 5" :key="i" :class="['w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold', i <= mockUser.levelNum ? 'bg-[#4A5F8B] text-white' : 'bg-[#1E2532] text-[#6B7C93]']">
            {{ i }}
          </span>
          <span class="ml-2 text-sm text-[#6B7C93]">{{ mockUser.tags }}</span>
        </div>
      </div>

      <div class="mt-8 border-t border-[#4A5F8B]/30">
        <div class="flex gap-8 mb-6">
          <button 
            v-for="tab in tabs" 
            :key="tab.id"
            @click="activeTab = tab.id"
            :class="['py-3 border-b-2 transition-colors', activeTab === tab.id ? 'border-[#4A5F8B] text-[#4A5F8B]' : 'border-transparent text-[#6B7C93] hover:text-white']"
          >
            {{ tab.name }} <span class="text-xs">({{ tab.count }})</span>
          </button>
        </div>

        <div v-if="activeTab === 'works'" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <div 
            v-for="post in mockPhotographyPosts" 
            :key="post.id"
            class="group relative aspect-[4/3] rounded-lg overflow-hidden bg-[#1E2532]"
          >
            <img :src="post.image" :alt="post.title" class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500" />
            <div class="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity">
              <div class="absolute bottom-4 left-4 right-4">
                <h3 class="text-white font-medium mb-2">{{ post.title }}</h3>
                <div class="flex items-center gap-4 text-sm text-white/80">
                  <span><i class="fa-solid fa-heart mr-1"></i>{{ post.likes }}</span>
                  <span><i class="fa-solid fa-comment mr-1"></i>{{ post.comments }}</span>
                  <span><i class="fa-solid fa-eye mr-1"></i>{{ post.views }}</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div v-if="activeTab === 'stats'" class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div class="bg-[#1E2532] rounded-lg p-6">
            <h3 class="text-lg font-semibold text-white mb-4">作品数据趋势</h3>
            <div class="h-48">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={monthlyStats}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#4A5F8B" />
                  <XAxis dataKey="month" tick={{ fill: '#B8C6D8', fontSize: 12 }} />
                  <YAxis tick={{ fill: '#B8C6D8' }} />
                  <Tooltip />
                  <Legend />
                  <Line type="monotone" dataKey="posts" stroke="#4A5F8B" strokeWidth={2} />
                  <Line type="monotone" dataKey="likes" stroke="#63B3ED" strokeWidth={2} />
                  <Line type="monotone" dataKey="views" stroke="#48BB78" strokeWidth={2} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div class="space-y-4">
            <div class="bg-[#1E2532] rounded-lg p-6">
              <h3 class="text-lg font-semibold text-white mb-4">作品统计</h3>
              <div class="grid grid-cols-2 gap-4">
                <div class="text-center p-3 bg-[#4A5F8B]/10 rounded-lg">
                  <p class="text-2xl font-bold text-[#4A5F8B]">1.2万</p>
                  <p class="text-xs text-[#6B7C93]">总浏览量</p>
                </div>
                <div class="text-center p-3 bg-green-500/10 rounded-lg">
                  <p class="text-2xl font-bold text-green-500">3.5千</p>
                  <p class="text-xs text-[#6B7C93]">总获赞</p>
                </div>
                <div class="text-center p-3 bg-blue-500/10 rounded-lg">
                  <p class="text-2xl font-bold text-blue-500">456</p>
                  <p class="text-xs text-[#6B7C93]">总评论</p>
                </div>
                <div class="text-center p-3 bg-purple-500/10 rounded-lg">
                  <p class="text-2xl font-bold text-purple-500">234</p>
                  <p class="text-xs text-[#6B7C93]">总收藏</p>
                </div>
              </div>
            </div>

            <div class="bg-[#1E2532] rounded-lg p-6">
              <h3 class="text-lg font-semibold text-white mb-4">标签分布</h3>
              <div class="flex flex-wrap gap-2">
                <span v-for="tag in tagDistribution" :key="tag.name" :class="['px-3 py-1 rounded-full text-sm', tag.color]">
                  {{ tag.name }} ({{ tag.count }})
                </span>
              </div>
            </div>
          </div>
        </div>

        <div v-if="activeTab === 'collections'" class="space-y-4">
          <div v-for="collection in collections" :key="collection.id" class="bg-[#1E2532] rounded-lg p-4">
            <div class="flex items-center gap-4">
              <img :src="collection.cover" :alt="collection.name" class="w-20 h-20 rounded-lg object-cover" />
              <div class="flex-1">
                <h3 class="text-white font-medium">{{ collection.name }}</h3>
                <p class="text-sm text-[#6B7C93]">{{ collection.count }} 个作品</p>
              </div>
              <span class="text-[#6B7C93]">{{ collection.date }}</span>
            </div>
          </div>
        </div>

        <div v-if="activeTab === 'about'" class="bg-[#1E2532] rounded-lg p-6">
          <h3 class="text-lg font-semibold text-white mb-4">关于我</h3>
          <div class="space-y-4 text-[#B8C6D8]">
            <p>{{ mockUser.bio }}</p>
            <div class="grid grid-cols-2 gap-4">
              <div>
                <p class="text-sm text-[#6B7C93]">加入时间</p>
                <p class="text-white">{{ mockUser.joinDate }}</p>
              </div>
              <div>
                <p class="text-sm text-[#6B7C93]">擅长题材</p>
                <p class="text-white">风光、人像</p>
              </div>
              <div>
                <p class="text-sm text-[#6B7C93]">常用器材</p>
                <p class="text-white">Sony A7R IV, Canon EOS R5</p>
              </div>
              <div>
                <p class="text-sm text-[#6B7C93]">代表作品</p>
                <p class="text-white">晨曦中的山峦、城市剪影</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';

const mockUser = {
  id: 'user-123',
  username: '@光影捕手',
  email: 'user@example.com',
  avatar: 'https://space.coze.cn/api/coze_space/gen_image?image_size=square&prompt=photographer%20avatar%20professional%20male%20portrait&sign=e53a45a0e2ef5ba23982d6db8693456b',
  bio: '热爱风光和人像摄影，喜欢探索城市中的几何美感和自然中的光影变化。',
  joinDate: '2023-01-15',
  followers: 123,
  following: 45,
  posts: 28,
  coverImage: 'https://space.coze.cn/api/coze_space/gen_image?image_size=landscape_16_9&prompt=photography%20studio%20background%20modern%20minimalist&sign=8848033bdf94e05818be4d57164ea015',
  level: '新锐摄影师',
  levelNum: 3,
  progress: 120,
  progressMax: 200,
  tags: '风光/人像双题材创作者',
  memberStatus: '银河会员·年卡',
  memberDaysLeft: 128
};

const mockPhotographyPosts = [
  {
    id: '1',
    title: '晨曦中的山峦',
    description: '捕捉清晨第一缕阳光洒在山峦上的壮丽景色',
    image: 'https://space.coze.cn/api/coze_space/gen_image?image_size=landscape_16_9&prompt=morning%20sunrise%20mountain%20landscape%20mist%20china&sign=a50c8d6084b10f76978cc2afb1ca29a9',
    author: { id: 'user-123', name: '@光影捕手', avatar: '' },
    likes: 324,
    comments: 45,
    tags: ['风光', '日出', '云海', '自然'],
    date: '2023-10-25',
    views: 1256,
    format: 'RAW',
    visibility: '公开',
    copyrightType: '独家授权'
  },
  {
    id: '2',
    title: '城市剪影',
    description: '从高处俯瞰城市天际线',
    image: 'https://space.coze.cn/api/coze_space/gen_image?image_size=landscape_16_9&prompt=city%20skyline%20silhouette%20sunset%20urban%20architecture%20modern&sign=8de72287cf83cda70c057b89bfc1d186',
    author: { id: 'user-123', name: '@光影捕手', avatar: '' },
    likes: 289,
    comments: 37,
    tags: ['城市', '建筑', '剪影', '夕阳'],
    date: '2023-10-22',
    views: 987,
    format: 'JPG',
    visibility: '公开',
    copyrightType: '非独家'
  },
  {
    id: '3',
    title: '海浪与礁石',
    description: '长时间曝光拍摄海浪拍打礁石',
    image: 'https://space.coze.cn/api/coze_space/gen_image?image_size=landscape_16_9&prompt=ocean%20waves%20crashing%20on%20rocks%20long%20exposure%20seascape&sign=e3c4cd3840caaaedc19f43f96183a958',
    author: { id: 'user-123', name: '@光影捕手', avatar: '' },
    likes: 412,
    comments: 53,
    tags: ['海景', '慢门', '自然', '礁石'],
    date: '2023-10-18',
    views: 1452,
    format: 'RAW',
    visibility: '仅好友可见',
    copyrightType: '独家授权'
  },
  {
    id: '4',
    title: '森林晨雾',
    description: '在山间森林中捕捉晨雾弥漫的神秘氛围',
    image: 'https://space.coze.cn/api/coze_space/gen_image?image_size=landscape_16_9&prompt=forest%20morning%20mist%20sunlight%20rays%20trees%20mystical&sign=0d866462637658cb7796789831e1cc68',
    author: { id: 'user-123', name: '@光影捕手', avatar: '' },
    likes: 387,
    comments: 49,
    tags: ['森林', '晨雾', '丁达尔', '自然'],
    date: '2023-10-15',
    views: 1123,
    format: 'RAW',
    visibility: '公开',
    copyrightType: '独家授权'
  },
  {
    id: '5',
    title: '古镇风情',
    description: '雨后的古镇石板路，倒映着古老的建筑',
    image: 'https://space.coze.cn/api/coze_space/gen_image?image_size=landscape_16_9&prompt=ancient%20town%20stone%20street%20reflection%20rain%20chinese%20architecture&sign=4e1f2c0a4a5f3c8b8e4d7a9c2b6e1d5f',
    author: { id: 'user-123', name: '@光影捕手', avatar: '' },
    likes: 256,
    comments: 32,
    tags: ['古镇', '人文', '建筑', '雨天'],
    date: '2023-10-10',
    views: 876,
    format: 'JPG',
    visibility: '公开',
    copyrightType: '非独家'
  },
  {
    id: '6',
    title: '星空银河',
    description: '在远离城市光污染的山区拍摄璀璨银河',
    image: 'https://space.coze.cn/api/coze_space/gen_image?image_size=landscape_16_9&prompt=milky%20way%20galaxy%20stars%20night%20sky%20long%20exposure%20astrophotography&sign=7a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d',
    author: { id: 'user-123', name: '@光影捕手', avatar: '' },
    likes: 521,
    comments: 67,
    tags: ['星空', '银河', '深空', '夜景'],
    date: '2023-10-05',
    views: 1890,
    format: 'RAW',
    visibility: '公开',
    copyrightType: '独家授权'
  }
];

const monthlyStats = [
  { month: '1月', posts: 2, likes: 120, views: 500 },
  { month: '2月', posts: 3, likes: 180, views: 800 },
  { month: '3月', posts: 1, likes: 90, views: 400 },
  { month: '4月', posts: 4, likes: 320, views: 1200 },
  { month: '5月', posts: 2, likes: 200, views: 900 },
  { month: '6月', posts: 3, likes: 280, views: 1100 },
  { month: '7月', posts: 5, likes: 450, views: 1800 },
  { month: '8月', posts: 2, likes: 160, views: 700 },
  { month: '9月', posts: 3, likes: 310, views: 1300 },
  { month: '10月', posts: 3, likes: 350, views: 1500 }
];

const tagDistribution = [
  { name: '风光', count: 12, color: 'bg-blue-500/20 text-blue-400' },
  { name: '人像', count: 8, color: 'bg-pink-500/20 text-pink-400' },
  { name: '城市', count: 5, color: 'bg-gray-500/20 text-gray-400' },
  { name: '建筑', count: 4, color: 'bg-yellow-500/20 text-yellow-400' },
  { name: '夜景', count: 3, color: 'bg-purple-500/20 text-purple-400' }
];

const collections = [
  { id: '1', name: '风光作品集', cover: 'https://space.coze.cn/api/coze_space/gen_image?image_size=landscape_16_9&prompt=landscape%20photography%20collection&sign=1a2b3c4d5e6f7a8b9c0d1e2f', count: 12, date: '2023-06-01' },
  { id: '2', name: '城市探索', cover: 'https://space.coze.cn/api/coze_space/gen_image?image_size=landscape_16_9&prompt=urban%20exploration%20photography&sign=2a3b4c5d6e7f8a9b0c1d2e3f', count: 8, date: '2023-08-15' },
  { id: '3', name: '人像精选', cover: 'https://space.coze.cn/api/coze_space/gen_image?image_size=landscape_16_9&prompt=portrait%20photography%20collection&sign=3a4b5c6d7e8f9a0b1c2d3e4f', count: 6, date: '2023-09-20' }
];

const tabs = [
  { id: 'works', name: '作品', count: mockPhotographyPosts.length },
  { id: 'stats', name: '数据', count: 0 },
  { id: 'collections', name: '收藏集', count: collections.length },
  { id: 'about', name: '关于', count: 0 }
];

const activeTab = ref('works');
</script>

// src/pages/Profile.tsx
import React, { useContext, useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { AuthContext } from '../contexts/authContext';
import { Empty } from '../components/Empty';
import { PhotographyCard } from '../components/PhotographyCard';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { toast } from 'sonner';

// 模拟用户数据 - 艺术风摄影平台
const mockUser = {
  id: 'user-123',
  username: '@光影捕手',
  email: 'user@example.com',
  avatar: 'https://space.coze.cn/api/coze_space/gen_image?image_size=square&prompt=photographer%20avatar%20professional%20male%20portrait&sign=e53a45a0e2ef5ba23982d6db8693456b',
  bio: '热爱风光和人像摄影，喜欢探索城市中的几何美感和自然中的光影变化。',
  joinDate: '2023-01-15',
  followers: 123,
  following: 45,
  posts: 28,
  coverImage: 'https://space.coze.cn/api/coze_space/gen_image?image_size=landscape_16_9&prompt=photography%20studio%20background%20modern%20minimalist&sign=8848033bdf94e05818be4d57164ea015',
  level: '新锐摄影师',
  levelNum: 3,
  progress: 120,
  progressMax: 200
};

// 模拟作品数据
const mockPhotographyPosts = [
  {
    id: "1",
    title: "黑白光影",
    description: "Leica Q2 Monochrom | 光圈: f/2.8 | 快门: 1/125s | ISO: 800\n极简主义黑白摄影，通过光影对比展现建筑的几何美感。",
    image: "https://space.coze.cn/api/coze_space/gen_image?image_size=landscape_16_9&prompt=black%20and%20white%20architecture%20geometric%20composition&sign=7f2b53dd226ab1ffb3f3eae704bada52",
    author: {
      id: "1",
      name: "极简摄影师林风",
      avatar: "https://space.coze.cn/api/coze_space/gen_image?image_size=square&prompt=minimalist%20photographer%20male%20serious&sign=fded36172bb86afa4dc326776156459c"
    },
    likes: 342,
    comments: 42,
    tags: ["极简主义", "黑白", "建筑", "徕卡"],
    date: "2023-10-25"
  },
  {
    id: "2",
    title: "胶片质感人像",
    description: "Canon AE-1 + 50mm f/1.4 | 光圈: f/2.0 | 快门: 1/125s | ISO: 400\n使用复古胶片相机拍摄的人像作品，自然柔和的色调与颗粒感。",
    image: "https://space.coze.cn/api/coze_space/gen_image?image_size=portrait_4_3&prompt=film%20photography%20portrait%20natural%20light%20soft%20colors&sign=c33fc387d9611cfbf5948eab73b3426b",
    author: {
      id: "2",
      name: "胶片摄影师安娜",
      avatar: "https://space.coze.cn/api/coze_space/gen_image?image_size=square&prompt=film%20photographer%20female%20vintage%20style&sign=5ec915debce76b46483be485e236cee2"
    },
    likes: 412,
    comments: 56,
    tags: ["人像", "胶片", "复古", "自然光"],
    date: "2023-10-24"
  },
  {
    id: "3",
    title: "暗调氛围",
    description: "Sony A7R IV + 35mm f/1.4 GM | 光圈: f/2.8 | 快门: 1/60s | ISO: 1600\n营造神秘而富有故事感的暗调氛围人像，强调光影层次与情绪表达。",
    image: "https://space.coze.cn/api/coze_space/gen_image?image_size=landscape_4_3&prompt=moody%20portrait%20low%20key%20dramatic%20lighting&sign=667d5b0612922acbe1a4e0355faeb800",
    author: {
      id: "3",
      name: "情绪摄影师李明",
      avatar: "https://space.coze.cn/api/coze_space/gen_image?image_size=square&prompt=moody%20photographer%20male%20creative&sign=b74f18a9e01693163824506fbbcc8c47"
    },
    likes: 389,
    comments: 49,
    tags: ["暗调", "氛围", "情绪", "人像"],
    date: "2023-10-23"
  },
  {
    id: "4",
    title: "极简静物",
    description: "Fujifilm GFX 100S + 120mm f/4 Macro | 光圈: f/5.6 | 快门: 1/125s | ISO: 200\n通过简洁的构图和柔和的光线，展现日常物品的质感与美感。",
    image: "https://space.coze.cn/api/coze_space/gen_image?image_size=square_hd&prompt=minimalist%20still%20life%20composition%20natural%20light&sign=d50543b56e3575f63623ea5055f2f854",
    author: {
      id: "4",
      name: "静物摄影师王静",
      avatar: "https://space.coze.cn/api/coze_space/gen_image?image_size=square&prompt=still%20life%20photographer%20female%20detail-oriented&sign=3bfd67c585c96ccf90c0560aadfc6c75"
    },
    likes: 276,
    comments: 32,
    tags: ["静物", "极简", "中画幅", "富士"],
    date: "2023-10-22"
  }
];

// 模拟创作数据趋势
const trendData = [
  { month: '8月', posts: 2, likes: 56, collections: 12, comments: 8 },
  { month: '9月', posts: 4, likes: 89, collections: 23, comments: 15 },
  { month: '10月', posts: 6, likes: 91, collections: 13, comments: 22 },
];

const Profile: React.FC = () => {
  const { id } = useParams();
  const { isAuthenticated, user } = useContext(AuthContext);
  const [activeTab, setActiveTab] = useState<'posts' | 'collections' | 'likes'>('posts');
  const navigate = useNavigate();
  
   // 初始化模拟用户数据
  const [profileUser, setProfileUser] = useState({
    id: 'user-123',
    username: '@光影捕手',
    email: 'user@example.com',
    avatar: 'https://space.coze.cn/api/coze_space/gen_image?image_size=square&prompt=photographer%20avatar%20professional%20male%20portrait&sign=e53a45a0e2ef5ba23982d6db8693456b',
    bio: '热爱风光和人像摄影，喜欢探索城市中的几何美感和自然中的光影变化。',
    joinDate: '2023-01-15',
    followers: 123,
    following: 45,
    posts: 28,
    likes: 236
  });
  
  // 检查是否是当前用户自己的主页
  const isCurrentUser = isAuthenticated && user?.id === profileUser.id;
  
  // 关注状态
  const [isFollowing, setIsFollowing] = useState(false);
  
  // 模拟作品数据
  const userPosts = mockPhotographyPosts;
  
  // 获取收藏作品
  const userCollections = mockPhotographyPosts.slice(0, 2);
  
  // 获取点赞作品
  const userLikes = mockPhotographyPosts.slice(1, 3);
  
  // 根据当前激活的标签显示对应的内容
  const displayPosts = activeTab === 'posts' ? userPosts : activeTab === 'collections' ? userCollections : userLikes;
  
  // 格式化日期为相对时间
  const formatRelativeTime = (dateString: string) => {
    const date = new Date(dateString);
    const now = new Date();
    const diffInSeconds = Math.floor((now.getTime() - date.getTime()) / 1000);
    
    if (diffInSeconds < 60) {
      return "刚刚";
    } else if (diffInSeconds < 3600) {
      const minutes = Math.floor(diffInSeconds / 60);
      return `${minutes}分钟前`;
    } else if (diffInSeconds < 86400) {
      const hours = Math.floor(diffInSeconds / 3600);
      return `${hours}小时前`;
    } else if (diffInSeconds < 604800) {
      const days = Math.floor(diffInSeconds / 86400);
      return `${days}天前`;
    } else {
      return date.toLocaleDateString('zh-CN');
    }
  };
  
  // 渲染用户作品集数据
  const renderUserPosts = () => {
    // 如果没有登录，显示提示
    if (!isAuthenticated) {
      return (
        <div className="text-center py-8">
          <p className="text-[#B8C6D8]">请先登录以查看更多内容</p>
          <button 
            onClick={() => navigate('/login')}
            className="inline-block mt-4 px-4 py-2 bg-[#4A5F8B] text-[#F5F7FA] rounded-lg hover:bg-[#6B7C93] transition-colors"
          >
            立即登录
          </button>
        </div>
      );
    }
    
     // 如果登录了但没有作品，显示空状态
    if (displayPosts.length === 0) {
      return (
        <Empty 
          type="empty"
          size="md"
          text={activeTab === 'posts' ? '暂无作品' : activeTab === 'collections' ? '暂无收藏' : '暂无点赞'}
          helperText={activeTab === 'posts' 
            ? '上传你的第一张作品，开始创作之旅吧！' 
            : activeTab === 'collections'
              ? '收藏喜欢的作品，建立你的灵感库'
              : '为喜欢的作品点赞，支持创作者'}
          icon="fa-image"
          actionText={activeTab === 'posts' ? '上传作品' : undefined}
          onActionClick={() => activeTab === 'posts' ? navigate('/profile-center/works') : undefined}
          backgroundColor="bg-[#2D3748]"
          textColor="text-[#F5F7FA]"
        />
      );
    }
    
    // 正常显示作品网格
    return (
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {displayPosts.map((post) => (
          <PhotographyCard key={post.id} post={post} />
        ))}
      </div>
    );
  };
  
  // 加载时的骨架屏（模拟）
  const renderSkeleton = () => {
    return (
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {[1, 2, 3, 4, 5, 6].map((item) => (
          <div key={item} className="bg-[#2D3748] rounded-lg overflow-hidden animate-pulse">
            <div className="h-48 bg-[#4A5F8B]"></div>
            <div className="p-4">
              <div className="h-4 bg-[#4A5F8B] rounded w-3/4 mb-3"></div>
              <div className="h-4 bg-[#4A5F8B] rounded w-full mb-2"></div>
              <div className="h-4 bg-[#4A5F8B] rounded w-full mb-4"></div>
              <div className="h-4 bg-[#4A5F8B] rounded w-1/2"></div>
            </div>
          </div>
        ))}
      </div>
    );
  };
  
  // 判断是否显示骨架屏（这里简单模拟）
  const showSkeleton = false;
  
  // 检查用户是否登录，如果没有登录，显示登录提示
  if (!isAuthenticated) {
    return (
      <div className="container mx-auto px-4 py-8 bg-[#1E2532] star-texture min-h-screen">
        <div className="flex flex-col items-center justify-center h-[60vh] text-center">
          <div className="w-16 h-16 bg-[#4A5F8B] rounded-full flex items-center justify-center text-[#F5F7FA] mb-4">
            <i className="fa-solid fa-user-lock text-2xl"></i>
          </div>
          <h2 className="text-2xl font-bold text-[#F5F7FA] mb-2">请先登录</h2>
          <p className="text-[#B8C6D8] mb-6 max-w-md">登录后查看用户主页内容，支持创作者</p>
          <button 
            onClick={() => navigate('/login')}
            className="px-6 py-3 bg-[#4A5F8B] text-[#F5F7FA] rounded-lg font-medium hover:bg-[#6B7C93] transition-colors"
          >
            立即登录
          </button>
        </div>
      </div>
    );
  }
  
  return (
    <div className="container mx-auto px-4 py-8 bg-[#1E2532] star-texture min-h-screen">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        {/* 返回按钮 */}
        <div className="mb-6">
          <button
            onClick={() => navigate('/')}
            className="inline-flex items-center space-x-1 text-[#B8C6D8]/70 hover:text-[#B8C6D8] transition-colors"
          >
            <i className="fa-solid fa-arrow-left"></i>
            <span>返回首页</span>
          </button>
        </div>
        
        {/* 个人资料卡片 */}
        <div className="bg-[#2D3748] rounded-xl overflow-hidden shadow-sm border border-[#4A5F8B] mb-8">
          {/* 封面图 */}
          <div className="h-64 overflow-hidden">
            <img
              src={mockUser.coverImage}
              alt="Cover"
              className="w-full h-full object-cover"
            />
          </div>
          
          {/* 用户信息 */}
          <div className="px-6 pb-6">
            <div className="flex flex-col md:flex-row -mt-20 mb-6">
              {/* 头像 */}
              <div className="flex-shrink-0 mb-4 md:mb-0 md:mr-6">
                <div className="w-40 h-40 rounded-full border-4 border-[#2D3748] overflow-hidden shadow-md border-[#4A5F8B]">
                  <img
                    src={profileUser.avatar}
                    alt="User avatar"
                    className="w-full h-full object-cover"
                  />
                </div>
              </div>
              
              {/* 用户信息和操作按钮 */}
              <div className="flex-1 flex flex-col justify-between">
                <div>
                  <div className="flex items-center">
                    <h1 className="text-2xl font-bold text-[#F5F7FA] mb-2">
                      {profileUser.username}
                    </h1>
                    <div className="ml-3 flex flex-wrap gap-2">
                      <span className="px-2 py-0.5 text-xs bg-[#4A5F8B]/20 text-[#B8C6D8] rounded">
                        {mockUser.level}
                      </span>
                    </div>
                  </div>
                  
                  {/* 等级和进度条 */}
                  <div className="flex items-center mb-4">
                    <span className="text-[#B8C6D8] text-sm mr-2">{mockUser.level} LV.{mockUser.levelNum}</span>
                    <div className="flex-1 h-2 bg-[#1E2532] rounded-full overflow-hidden mr-2">
                      <div 
                        className="h-full bg-[#4A5F8B]" 
                        style={{ width: `${(mockUser.progress / mockUser.progressMax) * 100}%` }}
                      ></div>
                    </div>
                    <span className="text-[#B8C6D8] text-xs">{mockUser.progress}/{mockUser.progressMax}</span>
                  </div>
                  
                  {/* 个人简介 */}
                  <p className="text-[#B8C6D8] mb-4">{profileUser.bio}</p>
                  
                  {/* 关注与粉丝 */}
                  <div className="flex items-center space-x-6">
                    <div className="flex items-center">
                      <span className="font-bold text-[#F5F7FA]">{profileUser.following}</span>
                      <span className="text-[#B8C6D8]/70 text-sm ml-1">关注</span>
                    </div>
                    <div className="flex items-center">
                      <span className="font-bold text-[#F5F7FA]">{profileUser.followers}</span>
                      <span className="text-[#B8C6D8]/70 text-sm ml-1">粉丝</span>
                    </div>
                  </div>
                </div>
                
                {/* 操作按钮 */}
                <div className="flex flex-wrap gap-3">
                  {isCurrentUser && (
                    <>
                      <button
                        onClick={() => navigate('/profile-center/settings')}
                        className="px-4 py-2 bg-[#4A5F8B] text-[#F5F7FA] border border-[#4A5F8B] rounded-lg font-medium hover:bg-[#6B7C93] transition-colors"
                      >
                        <i className="fa-solid fa-pen-to-square mr-2 text-[#F5F7FA]"></i> 编辑资料
                      </button>
                      <button
                        onClick={() => navigate('/profile-center')}
                        className="px-4 py-2 bg-[#4A5F8B] text-[#F5F7FA] border border-[#4A5F8B] rounded-lg font-medium hover:bg-[#6B7C93] transition-colors"
                      >
                        <i className="fa-solid fa-user-cog mr-2 text-[#F5F7FA]"></i> 进入个人中心
                      </button>
                    </>
                  )}
                  {!isCurrentUser && (
                     <div className="flex items-center space-x-3">
                     <button 
                       className={`px-4 py-2 rounded-lg font-medium transition-colors border ${
                         isFollowing 
                           ? 'bg-[#6B7C93] text-[#F5F7FA] border-[#6B7C93]' 
                           : 'bg-[#4A5F8B] text-[#F5F7FA] border-[#4A5F8B]'
                       }`}
                       onClick={() => {
                         if (!isAuthenticated) {
                           toast.info('请先登录后再关注用户');
                           return;
                         }
                         
                         setIsFollowing(!isFollowing);
                         toast.success(isFollowing ? '已取消关注' : `已关注 ${profileUser.username}`);
                       }}
                     >
                      {isFollowing ? (
                        <>
                          <i className="fa-solid fa-check mr-2 text-[#F5F7FA]"></i> 已关注
                        </>
                      ) : (
                        <>
                          <i className="fa-solid fa-plus mr-2 text-[#F5F7FA]"></i> 关注
                        </>
                      )}
                    </button>
                     <button 
                       onClick={async () => {
                         try {
                           await navigator.clipboard.writeText(`${window.location.origin}/profile/${profileUser.id}`);
                           toast.success('用户主页链接已复制到剪贴板');
                         } catch (err) {
                           toast.error('复制失败，请手动复制');
                         }
                       }}
                       className="p-2 bg-[#1E2532] text-[#B8C6D8] rounded-lg hover:bg-[#4A5F8B] hover:text-[#F5F7FA] transition-colors border border-[#4A5F8B] relative z-10"
                       title="分享用户主页"
                     >
                       <i className="fa-solid fa-share-nodes"></i>
                     </button>
                     </div>
                  )}
                </div>
              </div>
            </div>
            
            {/* 统计数据 */}
            <div className="flex flex-wrap border-t border-[#4A5F8B] pt-4">
              <div className="mr-8 mb-2">
                <div className="flex items-center space-x-1">
                  <span className="text-xl font-bold text-[#F5F7FA]">
                    {profileUser.posts}
                  </span>
                  <i className="fa-solid fa-image text-[#B8C6D8]"></i>
                </div>
                <span className="text-sm text-[#B8C6D8]">作品</span>
              </div>
              <div className="mr-8 mb-2">
                <div className="flex items-center space-x-1">
                  <span className="text-xl font-bold text-[#F5F7FA]">
                    {profileUser.likes}
                  </span>
                  <i className="fa-solid fa-heart text-[#B8C6D8]"></i>
                </div>
                <span className="text-sm text-[#B8C6D8]">获赞</span>
              </div>
              <div className="mr-8 mb-2">
                <div className="flex items-center space-x-1">
                  <span className="text-xl font-bold text-[#F5F7FA]">
                    48
                  </span>
                  <i className="fa-solid fa-bookmark text-[#B8C6D8]"></i>
                </div>
                <span className="text-sm text-[#B8C6D8]">收藏</span>
              </div>
            </div>
          </div>
        </div>
        
        {/* 内容标签页 */}
        <div className="bg-[#2D3748] rounded-xl shadow-sm border border-[#4A5F8B] mb-8">
          <div className="flex border-b border-[#4A5F8B]">
            <button
              onClick={() => {
                setActiveTab('posts');
                navigate(`/profile/${profileUser.id}`);
              }}
              className={`flex-1 py-4 px-6 text-center font-medium transition-colors ${
                activeTab === 'posts'
                  ? 'text-[#F5F7FA] border-b-2 border-[#4A5F8B]'
                  : 'text-[#B8C6D8]/70 hover:text-[#F5F7FA]'
              }`}
            >
              作品 ({profileUser.posts})
            </button>
            <button
              onClick={() => {
                setActiveTab('collections');
                navigate(`/profile/${profileUser.id}/collections`);
              }}
              className={`flex-1 py-4 px-6 text-center font-medium transition-colors ${
                activeTab === 'collections'
                  ? 'text-[#F5F7FA] border-b-2 border-[#4A5F8B]'
                  : 'text-[#B8C6D8]/70 hover:text-[#F5F7FA]'
              }`}
            >
              收藏 (48)
            </button>
            <button
              onClick={() => {
                setActiveTab('likes');
                navigate(`/profile/${profileUser.id}/likes`);
              }}
              className={`flex-1 py-4 px-6 text-center font-medium transition-colors ${
                activeTab === 'likes'
                  ? 'text-[#F5F7FA] border-b-2 border-[#4A5F8B]'
                  : 'text-[#B8C6D8]/70 hover:text-[#F5F7FA]'
              }`}
            >
              点赞 ({profileUser.likes})
            </button>
          </div>
          
          {/* 创作数据趋势图 */}
          {activeTab === 'posts' && isCurrentUser && (
            <div className="p-6 border-b border-[#4A5F8B]">
              <h2 className="text-xl font-bold text-[#F5F7FA] mb-4">创作数据</h2>
              <div className="h-64">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={trendData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#4A5F8B" />
                    <XAxis dataKey="month" stroke="#B8C6D8" />
                    <YAxis stroke="#B8C6D8" />
                    <Tooltip contentStyle={{ backgroundColor: '#2D3748', borderColor: '#4A5F8B', color: '#F5F7FA' }} />
                    <Legend />
                    <Line type="monotone" dataKey="posts" stroke="#4A5F8B" strokeWidth={2} dot={{ r: 4 }} activeDot={{ r: 6 }} name="作品数" />
                    <Line type="monotone" dataKey="likes" stroke="#B8C6D8" strokeWidth={2} dot={{ r: 4 }} activeDot={{ r: 6 }} name="获赞数" />
                    <Line type="monotone" dataKey="collections" stroke="#6B7C93" strokeWidth={2} dot={{ r: 4 }} activeDot={{ r: 6 }} name="收藏数" />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>
          )}
          
          {/* 内容区域 */}
          <div className="p-6">
            {showSkeleton ? renderSkeleton() : renderUserPosts()}
            
            {/* 加载更多按钮 */}
            {displayPosts.length > 0 && (
              <div className="mt-10 text-center">
                <button
                  onClick={() => navigate('/login')}
                  className="inline-flex items-center px-6 py-3 bg-[#2D3748] text-[#B8C6D8] border border-[#4A5F8B] hover:bg-[#4A5F8B] hover:text-[#F5F7FA] rounded-lg font-medium transition-colors"
                >
                  登录查看更多内容
                </button>
              </div>
            )}
          </div>
        </div>
      </motion.div>
    </div>
  );
};

export default Profile;
