// src/components/PhotographyCard.tsx
// PhotographyCard.tsx - 卡片hover效果详细描述：
// 1. 卡片容器：当鼠标悬停时，卡片会向上平移5个像素(y: -5)，同时边框颜色变为蓝色(#4A5F8B)，整体产生一种轻微上浮的效果
// 2. 图片：鼠标悬停在图片上时，图片会以1.05的比例进行缩放，增强视觉焦点
// 3. 作者名称链接：当鼠标悬停时，作者名称的文字颜色变为蓝色(#4A5F8B)
// 4. 标题链接：当鼠标悬停时，作品标题的文字颜色变为蓝色(#4A5F8B)
// 5. 点赞按钮：当鼠标悬停时，点赞按钮的文字颜色变为蓝色(#4A5F8B)
// 6. 评论按钮：当鼠标悬停时，评论按钮的文字颜色变为蓝色(#4A5F8B)
// 7. 收藏按钮：当鼠标悬停时，收藏按钮的文字颜色变为蓝色(#4A5F8B)

import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { useLikeAndBookmark } from '../hooks/useLikeAndBookmark';

// 摄影作品类型定义
export interface PhotographyPost {
  id: string;
  title: string;
  description: string;
  image: string;
  author: {
    id: string;
    name: string;
    avatar: string;
  };
  likes: number;
  comments: number;
  collections: number;
  tags: string[];
  date: string;
}

// 摄影卡片组件
interface PhotographyCardProps {
  post: PhotographyPost;
}

export const PhotographyCard: React.FC<PhotographyCardProps> = ({ post }) => {
  // 使用自定义 hook 管理点赞和收藏状态
  const { 
    isLiked, 
    isBookmarked, 
    likeCount, 
    collectionCount, 
    handleLike, 
    handleBookmark 
  } = useLikeAndBookmark(post.id, post.likes, post.collections);

  // handleLike 和 handleBookmark 已在 useLikeAndBookmark hook 中定义

  // 提取设备参数信息
  const getEquipmentParams = () => {
    const firstLine = post.description.split('\n')[0];
    // 检查是否包含设备参数格式
    if (firstLine.includes('|')) {
      return firstLine;
    }
    return '';
  };

  const equipmentParams = getEquipmentParams();

  return (
    <motion.div
      whileHover={{ y: -5, borderColor: '#4A5F8B' }}
      className="bg-[#2D3748] rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-shadow border border-[#4A5F8B] h-[500px] flex flex-col"
    >
      {/* 图片容器 */}
      <div className="relative flex-shrink-0">
        <Link to={`/photo/${post.id}`} className="block">
          <motion.img
            whileHover={{ scale: 1.05 }}
            transition={{ duration: 0.3 }}
            src={post.image}
            alt={post.title}
            className="w-full h-60 object-cover"
          />
        </Link>
        
        {/* 标签 - 作品标签浅蓝灰 #4A5F8B + 浅白 #F5F7FA */}
        <div className="absolute top-3 right-3 flex space-x-2">
          {post.tags.slice(0, 2).map((tag, index) => (
            <span
              key={index}
              className="px-2 py-1 bg-[#4A5F8B] text-[#F5F7FA] text-xs rounded-full border border-[#4A5F8B]"
            >
              #{tag}
            </span>
          ))}
          {post.tags.length > 2 && (
            <span className="px-2 py-1 bg-[#4A5F8B] text-[#F5F7FA] text-xs rounded-full border border-[#4A5F8B]">
              +{post.tags.length - 2}
            </span>
          )}
        </div>
      </div>

      {/* 内容容器 */}
      <div className="p-5 flex flex-col flex-grow">
        {/* 作者信息 */}
        <div className="flex items-center mb-3">
          <Link to={`/profile/${post.author.id}`} className="block mr-3">
            <img
              src={post.author.avatar}
              alt={post.author.name}
              className="w-8 h-8 rounded-full object-cover border border-[#B8C6D8]"
            />
          </Link>
          <div>
            <Link
              to={`/profile/${post.author.id}`}
              className="block font-medium text-[#F5F7FA] hover:text-[#4A5F8B] transition-colors"
            >
              {post.author.name}
            </Link>
            <p className="text-xs text-[#B8C6D8]">
              {post.date}
            </p>
          </div>
        </div>

        {/* 标题 */}
        <Link to={`/photo/${post.id}`} className="block mb-2">
          <h3 className="text-lg font-bold text-[#F5F7FA] hover:text-[#4A5F8B] transition-colors">
            {post.title}
          </h3>
        </Link>

        {/* 设备参数 */}
         {equipmentParams && (
          <p className="text-xs text-[#B8C6D8] mb-4 font-mono">{equipmentParams}</p>
        )}

        {/* 互动按钮 - 互动数据 (点赞/评论) 浅冷灰 #B8C6D8 */}
        <div className="flex items-center justify-between mt-auto">
          <div className="flex items-center space-x-4">
            <button
              onClick={handleLike}
              className={`flex items-center space-x-1 text-sm transition-colors ${
                isLiked
                  ? 'text-red-500'
                  : 'text-[#B8C6D8] hover:text-red-500'
              }`}
              aria-label={isLiked ? "取消点赞" : "点赞"}
            >
              <motion.i
                animate={isLiked ? { scale: [1, 1.2, 1] } : {}}
                transition={{ duration: 0.3 }}
                className={`fa-solid ${isLiked ? 'fa-heart' : 'fa-heart'}`}
              ></motion.i>
              <span>{likeCount}</span>
            </button>
            <Link
              to={`/photo/${post.id}#comments`}
              className="flex items-center space-x-1 text-sm text-[#B8C6D8] hover:text-[#4A5F8B] transition-colors"
            >
              <i className="fa-solid fa-comment"></i>
              <span>{post.comments}</span>
            </Link>
          </div>
          
            <button 
              onClick={handleBookmark}
              className={`text-sm transition-colors ${
                isBookmarked
                  ? 'text-yellow-500'
                  : 'text-[#B8C6D8] hover:text-yellow-500'
              }`}
              aria-label={isBookmarked ? "取消收藏" : "收藏"}
            >
              <i className="fa-solid fa-bookmark"></i>
              <span className="ml-1">{collectionCount}</span>
            </button>
        </div>
      </div>
    </motion.div>
  );
};

// fronted/src/components/PhotographyCard.vue
<template>
  <div
    class="photography-card"
    :class="{ 'card-hovered': isHovered }"
    @mouseenter="isHovered = true"
    @mouseleave="isHovered = false"
  >
    <div class="card-image-wrapper">
      <router-link :to="`/photo-detail/${post.id}`" class="card-image-link">
        <LazyImage :src="post.image" :alt="post.title" />
        <div class="image-overlay">
          <div class="overlay-content">
            <div class="quick-actions">
              <button
                @click.stop="handleLike"
                :class="['action-btn', { active: isLiked }]"
                :aria-label="isLiked ? '取消点赞' : '点赞'"
              >
                <i :class="['fa-solid fa-heart', isLiked ? 'heart-pulse' : '']"></i>
                <span>{{ likeCount }}</span>
              </button>
              <button
                @click.stop="handleBookmark"
                :class="['action-btn', { active: isBookmarked }]"
                :aria-label="isBookmarked ? '取消收藏' : '收藏'"
              >
                <i class="fa-solid fa-bookmark"></i>
                <span>{{ collectionCount }}</span>
              </button>
            </div>
          </div>
        </div>
      </router-link>
      
      <div class="tag-overlay">
        <span
          v-for="(tag, index) in post.tags.slice(0, 2)"
          :key="index"
          class="tag-badge"
        >
          #{{ tag }}
        </span>
        <span v-if="post.tags.length > 2" class="tag-badge">
          +{{ post.tags.length - 2 }}
        </span>
      </div>
    </div>

    <div class="card-content">
      <div class="author-section">
        <router-link :to="`/profile/${post.author.id}`" class="author-avatar-link">
          <img
            :src="post.author.avatar"
            :alt="post.author.name"
            class="author-avatar"
            loading="lazy"
          />
          <div class="avatar-border"></div>
        </router-link>
        <div class="author-info">
          <router-link
            :to="`/profile/${post.author.id}`"
            class="author-name"
          >
            {{ post.author.name }}
          </router-link>
          <p class="post-date">
            <i class="fa-regular fa-calendar mr-1"></i>
            {{ post.date }}
          </p>
        </div>
      </div>

      <router-link :to="`/photo-detail/${post.id}`" class="card-title-link">
        <h3 class="card-title">{{ post.title }}</h3>
      </router-link>

      <p v-if="equipmentParams" class="equipment-params">
        {{ equipmentParams }}
      </p>

      <div class="card-footer">
        <div class="footer-actions">
          <router-link
            :to="`/photo/${post.id}#comments`"
            class="footer-link"
          >
            <i class="fa-regular fa-comment"></i>
            <span>{{ post.comments }} 评论</span>
          </router-link>
          <div class="footer-stats">
            <span class="stat-item">
              <i class="fa-regular fa-eye"></i>
              {{ Math.floor(Math.random() * 5000 + 1000).toLocaleString() }}
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import LazyImage from './LazyImage.vue';

export interface PhotographyPost {
  id: string;
  title: string;
  description: string;
  image: string;
  author: {
    id: string;
    name: string;
    avatar: string;
  };
  likes: number;
  comments: number;
  collections: number;
  tags: string[];
  date: string;
}

const props = defineProps<{
  post: PhotographyPost;
}>();

const isHovered = ref(false);
const isLiked = ref(false);
const isBookmarked = ref(false);
const likeCount = ref(props.post.likes);
const collectionCount = ref(props.post.collections);

const equipmentParams = computed(() => {
  const firstLine = props.post.description.split('\n')[0];
  if (firstLine.includes('|')) {
    return firstLine;
  }
  return '';
});

const handleLike = () => {
  isLiked.value = !isLiked.value;
  likeCount.value += isLiked.value ? 1 : -1;
};

const handleBookmark = () => {
  isBookmarked.value = !isBookmarked.value;
  collectionCount.value += isBookmarked.value ? 1 : -1;
};
</script>

<style scoped>
.photography-card {
  background: #2D3748;
  border-radius: 16px;
  overflow: hidden;
  border: 1px solid #4A5F8B;
  transition: transform 0.4s cubic-bezier(0.16, 1, 0.3, 1), box-shadow 0.4s cubic-bezier(0.16, 1, 0.3, 1), border-color 0.4s cubic-bezier(0.16, 1, 0.3, 1);
  display: flex;
  flex-direction: column;
  height: 100%;
}

.photography-card:hover {
  transform: translateY(-8px);
  box-shadow: 0 20px 40px -12px rgba(74, 95, 139, 0.3);
  border-color: #6B7C93;
}

.card-image-wrapper {
  position: relative;
  aspect-ratio: 4/3;
  overflow: hidden;
}

.card-image-link {
  display: block;
  width: 100%;
  height: 100%;
}

.image-overlay {
  position: absolute;
  inset: 0;
  background: linear-gradient(to top, rgba(30, 37, 50, 0.9) 0%, transparent 50%);
  opacity: 0;
  transition: opacity 0.4s cubic-bezier(0.16, 1, 0.3, 1);
  display: flex;
  align-items: flex-end;
  padding: 16px;
}

.card-hovered .image-overlay {
  opacity: 1;
}

.overlay-content {
  width: 100%;
}

.quick-actions {
  display: flex;
  gap: 12px;
  justify-content: center;
}

.action-btn {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 10px 20px;
  background: rgba(74, 95, 139, 0.9);
  color: #F5F7FA;
  border: none;
  border-radius: 24px;
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: background-color 0.3s cubic-bezier(0.16, 1, 0.3, 1), transform 0.3s cubic-bezier(0.16, 1, 0.3, 1);
}

.action-btn:hover {
  background: #6B7C93;
  transform: scale(1.05);
}

.action-btn:active {
  transform: scale(0.95);
}

.action-btn.active {
  background: linear-gradient(135deg, #FF6B6B, #FF8E8E);
}

.action-btn.active .fa-heart {
  color: #fff;
}

.heart-pulse {
  animation: heartPulse 0.4s cubic-bezier(0.16, 1, 0.3, 1);
}

@keyframes heartPulse {
  0%, 100% { transform: scale(1); }
  50% { transform: scale(1.3); }
}

.tag-overlay {
  position: absolute;
  top: 12px;
  left: 12px;
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}

.tag-badge {
  padding: 6px 12px;
  background: rgba(74, 95, 139, 0.9);
  backdrop-filter: blur(10px);
  color: #F5F7FA;
  font-size: 11px;
  font-weight: 600;
  border-radius: 12px;
  border: 1px solid rgba(245, 247, 250, 0.1);
  transition: border-color 0.3s ease, transform 0.3s ease;
}

.card-hovered .tag-badge {
  transform: translateY(-2px);
}

.card-content {
  padding: 20px;
  flex: 1;
  display: flex;
  flex-direction: column;
}

.author-section {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 12px;
}

.author-avatar-link {
  position: relative;
}

.author-avatar {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  object-fit: cover;
  border: 2px solid transparent;
  transition: border-color 0.3s ease, transform 0.3s ease;
}

.avatar-border {
  position: absolute;
  inset: -3px;
  border-radius: 50%;
  border: 2px solid #4A5F8B;
  opacity: 0;
  transform: scale(0.8);
  transition: opacity 0.3s cubic-bezier(0.16, 1, 0.3, 1), transform 0.3s cubic-bezier(0.16, 1, 0.3, 1);
}

.card-hovered .avatar-border {
  opacity: 1;
  transform: scale(1);
}

.card-hovered .author-avatar {
  border-color: #4A5F8B;
  transform: scale(1.05);
}

.author-info {
  flex: 1;
  min-width: 0;
}

.author-name {
  font-size: 14px;
  font-weight: 600;
  color: #F5F7FA;
  text-decoration: none;
  display: block;
  transition: color 0.3s ease;
}

.author-name:hover {
  color: #4A5F8B;
}

.post-date {
  font-size: 12px;
  color: #6B7C93;
  margin: 2px 0 0 0;
}

.card-title-link {
  text-decoration: none;
  display: block;
  margin-bottom: 8px;
}

.card-title {
  font-size: 18px;
  font-weight: 700;
  color: #F5F7FA;
  margin: 0;
  line-height: 1.3;
  transition: color 0.3s ease;
}

.card-title-link:hover .card-title {
  color: #4A5F8B;
}

.equipment-params {
  font-size: 11px;
  color: #6B7C93;
  font-family: 'SF Mono', 'Courier New', monospace;
  background: rgba(74, 95, 139, 0.1);
  padding: 8px 12px;
  border-radius: 8px;
  margin: 8px 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.card-footer {
  margin-top: auto;
  padding-top: 12px;
  border-top: 1px solid rgba(74, 95, 139, 0.2);
}

.footer-actions {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.footer-link {
  display: flex;
  align-items: center;
  gap: 6px;
  color: #B8C6D8;
  text-decoration: none;
  font-size: 13px;
  transition: color 0.3s ease;
}

.footer-link:hover {
  color: #4A5F8B;
}

.footer-stats {
  display: flex;
  gap: 16px;
}

.stat-item {
  font-size: 13px;
  color: #6B7C93;
  display: flex;
  align-items: center;
  gap: 4px;
}
</style>
