// sheyingjiaoliu/frontend/src/components/common/GroupCard.vue
<template>
  <div :class="['bg-[#2D3748] rounded-xl overflow-hidden border border-[#4A5F8B]', className]">
    <div class="relative h-32">
      <img
        :src="coverImage"
        :alt="name"
        class="w-full h-full object-cover"
      />
      <div class="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent"></div>
      <div class="absolute bottom-3 left-3">
        <span :class="['px-2 py-1 rounded-full text-xs', categoryClass]">
          {{ category }}
        </span>
      </div>
    </div>
    
    <div class="p-4">
      <div class="flex items-center justify-between mb-3">
        <h3 class="text-lg font-semibold text-[#F5F7FA]">{{ name }}</h3>
        <span class="text-sm text-[#B8C6D8]">{{ memberCount }} 成员</span>
      </div>
      
      <p class="text-sm text-[#B8C6D8] mb-4 line-clamp-2">{{ description }}</p>
      
      <div class="flex items-center justify-between">
        <div class="flex items-center space-x-1">
          <div
            v-for="member in members"
            :key="member.id"
            :class="['w-8 h-8 rounded-full border-2', memberBorderClass, 'overflow-hidden']"
            :title="member.name"
          >
            <img :src="member.avatar" :alt="member.name" class="w-full h-full object-cover" />
          </div>
          <span v-if="memberCount > 4" class="w-8 h-8 rounded-full bg-[#4A5F8B] text-[#F5F7FA] flex items-center justify-center text-xs">
            +{{ memberCount - 4 }}
          </span>
        </div>
        
        <button :class="['px-3 py-1 rounded-lg text-sm font-medium transition-colors', buttonClass]">
          {{ isJoined ? '已加入' : '加入' }}
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

interface Member {
  id: string
  name: string
  avatar: string
}

interface Props {
  name: string
  description: string
  coverImage: string
  category: string
  memberCount: number
  members: Member[]
  isJoined?: boolean
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  isJoined: false,
  className: ''
})

const categoryClass = computed(() => {
  const categoryMap: Record<string, string> = {
    '摄影技巧': 'bg-blue-500/20 text-blue-400',
    '器材讨论': 'bg-purple-500/20 text-purple-400',
    '作品分享': 'bg-green-500/20 text-green-400',
    '活动组织': 'bg-orange-500/20 text-orange-400'
  }
  return categoryMap[props.category] || 'bg-gray-500/20 text-gray-400'
})

const memberBorderClass = computed(() => 'border-[#2D3748]')

const buttonClass = computed(() => {
  if (props.isJoined) {
    return 'bg-[#4A5F8B]/20 text-[#4A5F8B] border border-[#4A5F8B]'
  }
  return 'bg-[#4A5F8B] text-[#F5F7FA] hover:bg-[#6B7C93]'
})
</script>

// src/components/common/GroupCard.tsx
import React from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { useAuth } from '../../contexts/authContext';
import { toast } from 'sonner';

// 定义类型
interface GroupMember {
  id: string;
  name: string;
  avatar: string;
}

interface Group {
  id: string;
  name: string;
  description: string;
  members: number;
  posts: number;
  avatar: string;
  coverImage: string;
  joined: boolean;
  tags?: string[];
}

interface GroupCardProps {
  group: Group;
  onJoin?: (groupId: string) => void;
  onLeave?: (groupId: string) => void;
  onDelete?: (groupId: string) => void;
  canDelete?: boolean;
}

const GroupCard: React.FC<GroupCardProps> = (
  {
    group,
    onJoin,
    onLeave,
    onDelete,
    canDelete = false
  }
) => {
  const { isAuthenticated } = useAuth();

  const handleJoinLeave = () => {
    if (!isAuthenticated) {
      toast.info("请先登录后再操作");
      return;
    }

    if (group.joined) {
      if (window.confirm(`确定要退出"${group.name}"小组吗？`)) {
        if (onLeave) {
          onLeave(group.id);
        }
      }
    } else {
      if (onJoin) {
        onJoin(group.id);
      }
    }
  };

  const handleDelete = () => {
    if (window.confirm(`确定要删除"${group.name}"小组吗？此操作不可撤销。`)) {
      if (onDelete) {
        onDelete(group.id);
      }
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      className="bg-[#2D3748] rounded-xl overflow-hidden border border-[#4A5F8B] hover:shadow-lg transition-shadow"
    >
      {/* 封面图 */}
      <div className="relative h-32">
        <img
          src={group.coverImage}
          alt={`${group.name} cover`}
          className="w-full h-full object-cover"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
        
        {/* 小组头像 */}
        <div className="absolute bottom-0 left-4 transform translate-y-1/2">
          <div className="w-16 h-16 rounded-full border-4 border-[#2D3748] overflow-hidden">
            <img
              src={group.avatar}
              alt={group.name}
              className="w-full h-full object-cover"
            />
          </div>
        </div>
      </div>

      {/* 内容区域 */}
      <div className="p-4 pt-6">
        <div className="flex justify-between items-start mb-2">
          <h3 className="text-lg font-semibold text-white">
            <Link to={`/groups/${group.id}`} className="hover:text-[#63B3ED] transition-colors">
              {group.name}
            </Link>
          </h3>
          {canDelete && (
            <button
              onClick={handleDelete}
              className="p-1.5 rounded-lg hover:bg-red-500/20 text-red-400 transition-colors"
              title="删除小组"
            >
              <i className="fa-solid fa-trash-can text-sm" />
            </button>
          )}
        </div>

        <p className="text-[#B8C6D8] text-sm mb-3 line-clamp-2">
          {group.description}
        </p>

        {/* 标签 */}
        {group.tags && group.tags.length > 0 && (
          <div className="flex flex-wrap gap-1 mb-3">
            {group.tags.slice(0, 3).map((tag) => (
              <span
                key={tag}
                className="px-2 py-0.5 bg-[#4A5F8B]/30 text-[#B8C6D8] text-xs rounded-full"
              >
                {tag}
              </span>
            ))}
            {group.tags.length > 3 && (
              <span className="px-2 py-0.5 bg-[#4A5F8B]/30 text-[#B8C6D8] text-xs rounded-full">
                +{group.tags.length - 3}
              </span>
            )}
          </div>
        )}

        {/* 统计信息和操作按钮 */}
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4 text-sm">
            <span className="text-[#B8C6D8]">
              <i className="fa-solid fa-users mr-1" />
              {group.members}
            </span>
            <span className="text-[#B8C6D8]">
              <i className="fa-solid fa-message-circle mr-1" />
              {group.posts}
            </span>
          </div>

          <button
            onClick={handleJoinLeave}
            className={`px-4 py-1.5 rounded-lg text-sm font-medium transition-colors ${
              group.joined
                ? 'bg-[#4A5F8B]/30 text-[#B8C6D8] hover:bg-[#4A5F8B]/50'
                : 'bg-[#63B3ED] text-white hover:bg-[#4A9DE6]'
            }`}
          >
            {group.joined ? '退出' : '加入'}
          </button>
        </div>
      </div>
    </motion.div>
  );
};

export default GroupCard;
